namespace: ansilabnl
name: demo_one
version: 1.0.8
readme: README.md
authors:
  - JP Mens <jp@mens.de>
  - Ton Kersten <tonk@ansiblelab.nl>
description: A demo collection for training
license: 0BSD
tags:
  - demo
repository: https://github.com/ansilabnl/demo_one
dependencies: {}
build_ignore:
  - .tox
  - '*.tar.gz'
  - '*.tgz'
  - ansible.cfg
